// 오늘의 표현 후보 사전. id는 절대 재사용/변경하지 않는다 (localStorage 기록이 id로 연결됨).
const WORD_DB = [
  { id: 1, category: "회의", phrase: "Let's circle back to this.", meaning: "이건 나중에 다시 얘기해요", pron: "렛츠 서클 백 투 디스", example: "We're out of time, let's circle back to this next week.", level: "중" },
  { id: 2, category: "회의", phrase: "push back (on)", meaning: "반발하다, 이의를 제기하다", pron: "푸시 백", example: "The client pushed back on the new pricing.", level: "중" },
  { id: 3, category: "회의", phrase: "Let's table this for now.", meaning: "이건 일단 보류하죠", pron: "렛츠 테이블 디스 포 나우", example: "We're not aligned yet, let's table this for now.", level: "중" },
  { id: 4, category: "회의", phrase: "Can we take this offline?", meaning: "이건 따로 얘기할까요?", pron: "캔 위 테익 디스 오프라인", example: "This is a side topic, can we take this offline?", level: "하" },
  { id: 5, category: "회의", phrase: "Let's align on next steps.", meaning: "다음 단계를 맞춰봐요", pron: "렛츠 얼라인 온 넥스트 스텝스", example: "Before we wrap up, let's align on next steps.", level: "중" },
  { id: 6, category: "이메일", phrase: "As per my last email.", meaning: "지난 이메일에서 말씀드린 대로", pron: "애즈 퍼 마이 래스트 이메일", example: "As per my last email, the deadline is Friday.", level: "상" },
  { id: 7, category: "이메일", phrase: "Please find attached.", meaning: "첨부 파일 확인해주세요", pron: "플리즈 파인드 어태치트", example: "Please find attached the revised proposal.", level: "하" },
  { id: 8, category: "이메일", phrase: "Looking forward to your reply.", meaning: "답장 기다리겠습니다", pron: "룩킹 포워드 투 유어 리플라이", example: "Looking forward to your reply by Monday.", level: "하" },
  { id: 9, category: "이메일", phrase: "Just a gentle reminder.", meaning: "다시 한번 알려드려요", pron: "저스트 어 젠틀 리마인더", example: "Just a gentle reminder that the report is due today.", level: "하" },
  { id: 10, category: "이메일", phrase: "I'll follow up shortly.", meaning: "곧 후속 조치하겠습니다", pron: "아윌 팔로우 업 숏틀리", example: "I'll follow up shortly with the updated numbers.", level: "하" },
  { id: 11, category: "피드백", phrase: "I hear you, but...", meaning: "무슨 말인지 알겠지만...", pron: "아이 히어 유 벗", example: "I hear you, but we can't move the deadline.", level: "중" },
  { id: 12, category: "피드백", phrase: "That's a fair point.", meaning: "타당한 지적이네요", pron: "댓츠 어 페어 포인트", example: "That's a fair point, let me think about it.", level: "하" },
  { id: 13, category: "피드백", phrase: "Let's agree to disagree.", meaning: "서로 다른 의견인 걸로 해요", pron: "렛츠 어그리 투 디스어그리", example: "We won't align on this, let's agree to disagree.", level: "중" },
  { id: 14, category: "피드백", phrase: "Can you elaborate on that?", meaning: "좀 더 자세히 설명해줄래요?", pron: "캔 유 일래버레이트 온 댓", example: "Can you elaborate on that last point?", level: "중" },
  { id: 15, category: "피드백", phrase: "I'll take that on board.", meaning: "그 의견 반영할게요", pron: "아윌 테익 댓 온 보드", example: "Good point, I'll take that on board.", level: "상" },
  { id: 16, category: "스몰토크", phrase: "How's it going?", meaning: "요즘 어떻게 지내요?", pron: "하우즈 잇 고잉", example: "Hey, how's it going? Long time no see.", level: "하" },
  { id: 17, category: "스몰토크", phrase: "It's been a while.", meaning: "오랜만이네요", pron: "잇츠 빈 어 와일", example: "It's been a while since we last talked.", level: "하" },
  { id: 18, category: "스몰토크", phrase: "What have you been up to?", meaning: "요즘 뭐하고 지냈어요?", pron: "왓 해브 유 빈 업 투", example: "What have you been up to lately?", level: "하" },
  { id: 19, category: "스몰토크", phrase: "Small world!", meaning: "세상 좁네요!", pron: "스몰 월드", example: "You know him too? Small world!", level: "하" },
  { id: 20, category: "스몰토크", phrase: "Let's catch up sometime.", meaning: "언제 한번 밀린 얘기해요", pron: "렛츠 캐치 업 섬타임", example: "We should catch up sometime soon.", level: "하" },
  { id: 21, category: "인터뷰", phrase: "Walk me through your experience.", meaning: "경험을 처음부터 설명해주세요", pron: "워크 미 쓰루 유어 익스피리언스", example: "Can you walk me through your experience with Kubernetes?", level: "중" },
  { id: 22, category: "인터뷰", phrase: "What's your greatest strength?", meaning: "가장 큰 강점이 뭔가요?", pron: "왓츠 유어 그레이티스트 스트렝쓰", example: "What's your greatest strength for this role?", level: "하" },
  { id: 23, category: "인터뷰", phrase: "Tell me about a time when...", meaning: "~했던 때에 대해 말해주세요", pron: "텔 미 어바웃 어 타임 웬", example: "Tell me about a time when you missed a deadline.", level: "중" },
  { id: 24, category: "인터뷰", phrase: "Why should we hire you?", meaning: "왜 당신을 뽑아야 하나요?", pron: "와이 슈드 위 하이어 유", example: "Why should we hire you over other candidates?", level: "하" },
  { id: 25, category: "인터뷰", phrase: "Do you have any questions for us?", meaning: "저희에게 질문 있으신가요?", pron: "두 유 해브 애니 퀘스천스 포 어스", example: "Before we wrap up, do you have any questions for us?", level: "하" },
  { id: 26, category: "회의", phrase: "Let's touch base next week.", meaning: "다음 주에 다시 연락해요", pron: "렛츠 터치 베이스 넥스트 위크", example: "Let's touch base next week on progress.", level: "중" },
  { id: 27, category: "이메일", phrase: "Kindly advise.", meaning: "알려주시면 감사하겠습니다", pron: "카인들리 어드바이즈", example: "Kindly advise on the best time to call.", level: "중" },
  { id: 28, category: "피드백", phrase: "Let's course-correct.", meaning: "방향을 바로잡읍시다", pron: "렛츠 코스 커렉트", example: "The numbers are off, let's course-correct now.", level: "상" },
  { id: 29, category: "스몰토크", phrase: "No worries at all.", meaning: "전혀 걱정 마세요", pron: "노 워리즈 앳 올", example: "No worries at all, take your time.", level: "하" },
  { id: 30, category: "인터뷰", phrase: "I'm a quick learner.", meaning: "저는 빨리 배우는 편이에요", pron: "아임 어 퀵 러너", example: "I'm a quick learner and adapt fast to new tools.", level: "하" },
];
